parameters:
#    tree_tree.example.class: Tree\TreeBundle\Example

services:
    authentication:
         class: Tree\TreeBundle\AuthenticationController
#        arguments: [@service_id, "plain_value", %parameter%]
