Tree\TreeBundle\Entity\Chat:
    type: entity
    table: chat
    id: 
        id: 
            type: integer
            generator: { strategy: AUTO }
    fields:
        msgfrom:
            type: integer
            length: '7'
        msgto: 
            type: integer
            length: '7'
        message: 
            type: text
        sent:
            type: datetime
        recd:
            type: integer
            length: '7'        

