Tree\TreeBundle\Entity\Chatusers:
    type: entity
    table: users
    id:
        id: 
            type: integer
            generator: { strategy: AUTO }
    fields:
        uid:
            type: integer
            length: '11'
        username:
            type: string
            length: 30
        password:
            type: string
            length: 30
        email: 
            type: string
            length: 100
     
