Tree\TreeBundle\Entity\Language:
    type: entity
    table: parivar_language
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        language:
            type: string
            length: '30'
    
