Tree\TreeBundle\Entity\Usertoiprel:
    type: entity
    table: parivar_usertoiprel
    id: 
        id:
            type: integer
            length: '7'
            generator: { strategy:AUTO }
    fields:
        userid: 
            type: integer
            length: '7'
        login_ip:
            type: string
            length: '30'
        logout_ip: 
            type: string
            length: '30'

