Tree\TreeBundle\Entity\Accountlanguagerel:
    type: entity
    table: parivar_accountlanguagerel 
    id:
        id:
           type: integer
           generator: { strategy: AUTO }
    fields:
        userid:
           type: integer
           length: '7'
        languageid:
           type: integer
           length: '7'
        
