Tree\TreeBundle\Entity\Userchatblockrel:
    type: entity
    table: parivar_userchatblockrel
    id: 
        id: 
            type: integer
            length: '7'
            generator: { strategy: AUTO }
    fields:
        userid:
            type: integer
            length: 7
        relid:
           type: integer
           length: 7
